---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    network_mode: "host"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    network_mode: "host"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    network_mode: "host"
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    network_mode: "host"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://localhost:8081
      SERVER_PORT: 8082

  db-conta:
    image: postgres:14.5-alpine
    network_mode: "host"
    command: -p 15432
    volumes:
      - ./docker/db/conta.sql:/docker-entrypoint-initdb.d/conta.sql
    environment:
      - POSTGRES_USER=conta
      - POSTGRES_PASSWORD=conta123
      - POSTGRES_DB=conta
